runtime: custom
vm: true
api_version: 1

manual_scaling:
  instances: 1

env_variables:
  assets_dir: assets
  api_prefix: _api

handlers:

- url: /(.*\.(css|js))
  static_files: assets/\1
  upload: assets/(.*\.(css|js))

- url: /.*
  script: dynamic
